name = "geomIO"
uuid = "1698356d-72e0-4ca1-8773-07ef76f75400"
authors = ["Lucas Moser <lumoser@students.uni-mainz.de>", "Tobias Baumann", "Boris Kaus <kaus@uni-mainz.de>"]
version = "0.1.0"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
